# Generated by Django 4.1 on 2022-10-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_subproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='images',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
