# Generated by Django 4.1 on 2022-10-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_product_image_alter_subproduct_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproduct',
            old_name='images',
            new_name='image',
        ),
    ]
