# Generated by Django 4.1 on 2022-10-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_images_subproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
