# Generated by Django 4.1 on 2022-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_subproduct_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(max_length=500)),
                ('Hospital_Location', models.CharField(max_length=500)),
                ('Hospital_City', models.CharField(max_length=500)),
                ('Hospital_Id', models.CharField(max_length=500)),
                ('Hospital_Number', models.CharField(max_length=500)),
                ('Hospital_Email', models.CharField(max_length=500)),
                ('Hospital_Password', models.CharField(max_length=500)),
                ('UserType', models.CharField(max_length=500)),
            ],
        ),
    ]
